### PR TITLE
Update to kotlin 1.6.0, okio 3.0.0, ktoml 0.2.9

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Update Kotlin 1.5.31 -> 1.6.0
* Update okio 3.0.0-alpha.11 -> 3.0.0
* Update ktoml 0.2.6 -> 0.2.9 (ktoml-file built with okio-3.0.0)
* Remove `optIn`s

### CODE REVIEW

**Review by akuleshov7 — APPROVED** [review]
Mostly done with an upgrade of ktoml, please include the updated ktoml into this PR after it's done

**Comment by akuleshov7** [comment]
`readUtf8Line` and `System` are not working in okio3

**Comment by petertrr** [comment]
> FYI: `FileSystem.System` is not working in okio3 in common code:

Yes, that's why we have `commonNonJs` source set in save. They've changed it in one of the early alphas already. Common code should use the interface, and caller should inject actual FS implementation.

**Comment by petertrr** [comment]
@akuleshov7 actually we'll have to update Kotlin in this PR too, because build fails with incompatible ABI now.

**Review by akuleshov7 — APPROVED** [review]

**Pull request merged**
